#!/bin/bash

clear
if [[ $(pwd)/modules/global && $(pwd)/modules/menu && $(pwd)/modules/language && $(pwd)/modules/partitioning ]]; then
  source modules/global 
  source modules/menu
  source modules/language
  source modules/partitioning

  echo $(tput initc 8 000 500 500) $(tput setaf 8)
  echo $(tput bold)

  figlet -c -t -f slant "Ianarch"
  centrado "Telegram: @Ianeph | Github: https://github.com/jolmang"
  sleep 5

  clear
else
  echo "No se encuentra el archivo 'functions'"
  exit 1
fi

PrincipalMenu
